# Generated by Django 4.2.1 on 2023-05-13 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_animals', '0002_animal_animal_age_cannot_be_future_date_and_more'),
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shelter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app_animals.shelter'),
        ),
    ]
