# Generated by Django 4.2.1 on 2023-05-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_user_is_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='asked_for_upgrade',
            field=models.BooleanField(default=False),
        ),
    ]
