# Generated by Django 4.2.1 on 2023-05-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_animals', '0002_animal_animal_age_cannot_be_future_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
