# Generated by Django 4.2.1 on 2023-05-13 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_animals', '0003_animal_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='animals', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
